DROP TABLE INFO CASCADE CONSTRAINTS;

CREATE TABLE INFO(
    `ID` NUMBER(4) NOT NULL PRIMARY KEY,
    `LASTNAME` VARCHAR2(20) NOT NULL,
    `FIRSTNAME` VARCHAR2(20) NOT NULL,
    `COMMENT` VARCHAR2(40)
);

INSERT INTO INFO (ID, LASTNAME, FIRSTNAME, COMMENT) VALUES (1, 'Ivanovich', 'Ivan', 'men');
INSERT INTO INFO (ID, LASTNAME, FIRSTNAME, COMMENT) VALUES (2, 'Petrovich', 'P', '!!!!!');