DROP TABLE info CASCADE CONSTRAINTS;

CREATE TABLE info(
    ID NUMBER(4) NOT NULL PRIMARY KEY,
    LASTNAME VARCHAR2(20) NOT NULL,
    FIRSTNAME VARCHAR2(20) NOT NULL,
    COMMENT_TEXT VARCHAR2(40)
);

INSERT INTO info (ID, LASTNAME, FIRSTNAME, COMMENT_TEXT) VALUES (1, 'Ivanovich', 'Ivan', 'men');
INSERT INTO info (ID, LASTNAME, FIRSTNAME, COMMENT_TEXT) VALUES (2, 'Petrovich', 'P', '!!!!!');

COMMIT;